name: feature build & deploy

on:
  pull_request:
    types: [opened, reopened, synchronize]

concurrency:
  group: "feature-deploy"
  cancel-in-progress: false

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  set-vars:
    runs-on: ubuntu-latest
    outputs:
      ENV_NAME: ${{ steps.genEnvName.outputs.ENV_NAME }}
    steps:
      - id: genEnvName
        name: set env
        run: echo "ENV_NAME=${GITHUB_REF#refs/branch/}" | tr / - >> $GITHUB_OUTPUT

  build:
    needs: [set-vars]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: npm install
        run: npm ci

      - name: npm build
        run: npm run build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.set-vars.outputs.ENV_NAME }}

  deployment:
    needs: [set-vars, build]
    runs-on: ubuntu-latest
    environment:
      name: ${{ needs.set-vars.outputs.ENV_NAME }}
      url: https://${{ needs.set-vars.outputs.ENV_NAME }}-domigmail-dev.apps.sandbox-m2.ll9k.p1.openshiftapps.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login into openshift
        uses: ./.github/actions/oc-login
        with:
          namespace: ${{ env.OPENSHIFT_NAMESPACE }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}

      - name: list projects
        run: oc projects
